// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package types

type CommonResp struct {
	Code    int64       `json:"code" doc:"状态码"`
	Message string      `json:"message" doc:"消息"`
	Data    interface{} `json:"data" doc:"数据"`
	Token   string      `json:"token" doc:"凭证"`
}

type CreateUserReq struct {
	Username string `json:"username" validate:"required" doc:"用户名，必填"`
	Password string `json:"password" validate:"required" doc:"密码，必填"`
	Nickname string `json:"nickname" validate:"required" doc:"用户昵称，必填"`
	Role     string `json:"role" validate:"required,oneof=admin user" doc:"用户角色，必须是admin或user"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required" doc:"用户名，必填"`
	Password string `json:"password" validate:"required" doc:"密码，必填"`
}

type LoginResp struct {
}

type RegisterReq struct {
	Username        string `json:"username" validate:"required" doc:"用户名，必填"`
	Email           string `json:"email" validate:"required,email" doc:"邮箱地址，必填且格式正确"`
	Password        string `json:"password" validate:"required,min=6" doc:"密码，至少6位"`
	ConfirmPassword string `json:"confirmPassword" validate:"required,eqfield=Password" doc:"确认密码，必须与密码相同"`
	VerifyCode      string `json:"verifyCode" validate:"required,len=6" doc:"6位数字验证码"`
	Nickname        string `json:"nickname" validate:"required" doc:"用户昵称"`
}

type SendVerifyCodeReq struct {
	Email string `json:"email" validate:"required,email" doc:"邮箱地址，必填且格式正确"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id" validate:"required" doc:"用户ID，必填"`
	Nickname string `json:"nickname,optional" doc:"用户昵称，选填"`
	Avatar   string `json:"avatar,optional" doc:"用户头像URL，选填"`
	Role     string `json:"role,optional" validate:"omitempty,oneof=admin user" doc:"用户角色，选填，必须是admin或user"`
}

type UserInfo struct {
	Id       int64  `json:"id" doc:"用户ID"`
	Username string `json:"username" doc:"用户名"`
	Nickname string `json:"nickname" doc:"用户昵称"`
	Avatar   string `json:"avatar" doc:"用户头像URL"`
	Role     string `json:"role" doc:"用户角色：admin或user"`
}

type UserListReq struct {
	Page     int64  `form:"page,default=1" validate:"required,min=1" doc:"页码，从1开始"`
	PageSize int64  `form:"pageSize,default=20" validate:"required,min=1,max=100" doc:"每页数量，1-100"`
	Keyword  string `form:"keyword,optional" doc:"搜索关键词，可选"`
}

type UserListResp struct {
	Total int64      `json:"total" doc:"总记录数"`
	List  []UserInfo `json:"list" doc:"用户列表"`
}
