// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type LoginReq struct {
	Username string `json:"username" validate:"required" ` //用户名，必填
	Password string `json:"password" validate:"required" ` //密码，必填
}

type LoginResp struct {
	Token string `json:"token" doc:"token"` //token
}

type RegisterReq struct {
	Username        string `json:"username" validate:"required,min=3,max=50" `           //用户名，必填，长度3-50
	Email           string `json:"email" validate:"omitempty,email"`                     //邮箱，选填，格式为email
	Mobile          string `json:"mobile" validate:"omitempty,len=11"`                   //手机号，选填，必须为11位
	Password        string `json:"password" validate:"required,min=6,max=20"`            //密码，必填，至少6位，最多20位
	ConfirmPassword string `json:"confirmPassword" validate:"required,eqfield=Password"` //确认密码，必填，必须与密码相同
	VerifyCode      string `json:"verifyCode" validate:"required,len=6"`                 //6位数字验证码
	Nickname        string `json:"nickname" validate:"required,min=2,max=50"`            //用户昵称，必填，长度2-50
}
