// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginReq struct {
	Username string `json:"username" validate:"required" ` //用户名，必填
	Password string `json:"password" validate:"required" ` //密码，必填
}

type LoginResp struct {
	Token string `json:"token" doc:"token"` //token
}

type RegisterReq struct {
	Username        string `json:"username" validate:"required,min=3,max=50" `           //用户名，必填，长度3-50
	Password        string `json:"password" validate:"required,min=6,max=20"`            //密码，必填，至少6位，最多20位
	ConfirmPassword string `json:"confirmPassword" validate:"required,eqfield=Password"` //确认密码，必填，必须与密码相同
}

type SendVerifyCodeReq struct {
	Email string `json:"email" validate:"required,email"` //邮箱，必填，格式为email
}

type SendVerifyCodeResp struct {
	Code string `json:"code" doc:"code"` //验证码
}

type VerifyCodeReq struct {
	Email string `json:"email" validate:"required,email"` //邮箱，必填，格式为email
}
