// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddDepartmentReq struct {
	EntityId int64  `json:"entityId"` // 实体id
	Name     string `json:"name"`     // 部门名称
	Sort     int64  `json:"sort"`     // 排序
	ParentID int64  `json:"parentId"` // 父部门id
}

type DeleteDepartmentReq struct {
	ID int64 `form:"id"` // 部门id
}

type DepartmentListReq struct {
	Keyword  string `form:"keyword,optional"` //关键字
	Page     int64  `form:"page"`             // 页码
	PageSize int64  `form:"pageSize"`         // 每页条数
}

type DepartmentListResp struct {
	Total int64        `json:"total"` // 总数
	List  []Department `json:"list"`  // 部门列表
}

type TopDepartmentReq struct {
	ParentID int64 `json:"parentId"` // 父部门id
}

type TopDepartmentResp struct {
	List []TopDepartment `json:"list"` // 部门列表
}

type UpdateDepartmentReq struct {
	ID       int64  `json:"id"`       // 部门id
	Name     string `json:"name"`     // 部门名称
	Sort     int64  `json:"sort"`     // 排序
	Status   int64  `json:"status"`   //状态
	ParentID int64  `json:"parentId"` // 父部门id
}
