// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AuthItem struct {
	ID       int    `json:"id"`
	Title    string `json:"title"`
	AuthMark string `json:"auth_mark"`
}

type Department struct {
	ID         int64        `json:"id"`         // 部门id
	Name       string       `json:"name"`       // 部门名称
	Sort       int64        `json:"sort"`       // 排序
	Status     int64        `json:"status"`     // 状态
	CreateTime string       `json:"createTime"` // 创建时间
	UpdateTime string       `json:"updateTime"` // 更新时间
	Children   []Department `json:"children"`   // 子部门
}

type Meta struct {
	Title             string     `json:"title"`
	Icon              string     `json:"icon,omitempty"`
	KeepAlive         bool       `json:"keepAlive"`
	ShowTextBadge     string     `json:"showTextBadge,omitempty"`
	ShowBadge         bool       `json:"showBadge,omitempty"`
	Link              string     `json:"link,omitempty"`
	IsIframe          bool       `json:"isIframe,omitempty"`
	IsHide            bool       `json:"isHide,omitempty"`
	IsHideTab         bool       `json:"isHideTab,omitempty"`
	IsInMainContainer bool       `json:"isInMainContainer,omitempty"`
	AuthList          []AuthItem `json:"authList,omitempty"`
}

type Policy struct {
	Object string `json:"object"` // 对象
	Action string `json:"action"` // 动作
}

type Role struct {
	ID          int64  `json:"id"`          // 角色ID
	Name        string `json:"name"`        // 角色名称
	Description string `json:"description"` // 角色描述
	CreateTime  string `json:"createTime"`  // 创建时间
	UpdateTime  string `json:"updateTime"`  // 更新时间
	Status      int64  `json:"status"`      // 状态
}

type Route struct {
	ID        int      `json:"id"`   //路由id
	Name      string   `json:"name"` //路由名称
	Path      string   `json:"path"` //
	Component string   `json:"component"`
	Meta      Meta     `json:"meta"`
	Children  []*Route `json:"children,omitempty"`
}

type TopDepartment struct {
	ID   int64  `json:"id"`   // 部门id
	Name string `json:"name"` // 部门名称
}
