// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateUserReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	RoleID   int64  `json:"role_id"`
}

type CreateUserResp struct {
}

type GetUserListReq struct {
	Current int64 `form:"current"`
	Size    int64 `form:"size"`
}

type GetUserListResp struct {
	List    []UserInfoResp `json:"list"`
	Size    int64          `json:"size"`
	Current int64          `json:"current"`
	Total   int64          `json:"total"`
}

type UserInfoResp struct {
	UserName   string  `json:"username"`    //用户名
	Email      string  `json:"email"`       //邮箱
	Mobile     string  `json:"mobile"`      //手机号
	Nickname   string  `json:"nickname"`    //昵称
	Avatar     string  `json:"avatar"`      //头像
	RoleIDs    []int64 `json:"role_ids"`    //角色ID
	Status     int64   `json:"status"`      //状态
	CreateTime string  `json:"create_time"` //创建时间
	UpdateTime string  `json:"update_time"` //更新时间
}
