// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type UserInfoResp struct {
	UserName   string `json:"username"`    //用户名
	Email      string `json:"email"`       //邮箱
	Mobile     string `json:"mobile"`      //手机号
	Nickname   string `json:"nickname"`    //昵称
	Avatar     string `json:"avatar"`      //头像
	RoleID     int64  `json:"role_id"`     //角色ID
	Status     int64  `json:"status"`      //状态
	CreateTime string `json:"create_time"` //创建时间
	UpdateTime string `json:"update_time"` //更新时间
}
