// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package route

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"admin-server/api/internal/pkg/globalkey"
	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	menuAuthFieldNames          = builder.RawFieldNames(&MenuAuth{})
	menuAuthRows                = strings.Join(menuAuthFieldNames, ",")
	menuAuthRowsExpectAutoSet   = strings.Join(stringx.Remove(menuAuthFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	menuAuthRowsWithPlaceHolder = strings.Join(stringx.Remove(menuAuthFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMenuAuthIdPrefix = "cache:menuAuth:id:"
)

type (
	menuAuthModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *MenuAuth) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MenuAuth, error)
		Update(ctx context.Context, session sqlx.Session, data *MenuAuth) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *MenuAuth) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*MenuAuth, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*MenuAuth, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*MenuAuth, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*MenuAuth, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*MenuAuth, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultMenuAuthModel struct {
		sqlc.CachedConn
		table string
	}

	MenuAuth struct {
		Id         int64        `db:"id"`          // 权限ID
		MenuId     int64        `db:"menu_id"`     // 菜单ID
		Title      string       `db:"title"`       // 权限标题
		AuthMark   string       `db:"auth_mark"`   // 权限标识
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 删除时间
		DelState   int64        `db:"del_state"`   // 删除状态 0:未删除 1:已删除
	}
)

func newMenuAuthModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMenuAuthModel {
	return &defaultMenuAuthModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`menu_auth`",
	}
}

func (m *defaultMenuAuthModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	menuAuthIdKey := fmt.Sprintf("%s%v", cacheMenuAuthIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, menuAuthIdKey)
	return err
}
func (m *defaultMenuAuthModel) FindOne(ctx context.Context, id int64) (*MenuAuth, error) {
	menuAuthIdKey := fmt.Sprintf("%s%v", cacheMenuAuthIdPrefix, id)
	var resp MenuAuth
	err := m.QueryRowCtx(ctx, &resp, menuAuthIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", menuAuthRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMenuAuthModel) Insert(ctx context.Context, session sqlx.Session, data *MenuAuth) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{}
	data.DelState = globalkey.DelStateNo
	menuAuthIdKey := fmt.Sprintf("%s%v", cacheMenuAuthIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, menuAuthRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.MenuId, data.Title, data.AuthMark, data.DeleteTime, data.DelState)
		}
		return conn.ExecCtx(ctx, query, data.MenuId, data.Title, data.AuthMark, data.DeleteTime, data.DelState)
	}, menuAuthIdKey)
}

func (m *defaultMenuAuthModel) Update(ctx context.Context, session sqlx.Session, data *MenuAuth) (sql.Result, error) {
	menuAuthIdKey := fmt.Sprintf("%s%v", cacheMenuAuthIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, menuAuthRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.MenuId, data.Title, data.AuthMark, data.DeleteTime, data.DelState, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.MenuId, data.Title, data.AuthMark, data.DeleteTime, data.DelState, data.Id)
	}, menuAuthIdKey)
}

func (m *defaultMenuAuthModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *MenuAuth) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if _, err := m.Update(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "MenuAuthModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultMenuAuthModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultMenuAuthModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultMenuAuthModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*MenuAuth, error) {

	builder = builder.Columns(menuAuthRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*MenuAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultMenuAuthModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*MenuAuth, error) {

	builder = builder.Columns(menuAuthRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*MenuAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultMenuAuthModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*MenuAuth, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(menuAuthRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*MenuAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultMenuAuthModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*MenuAuth, error) {

	builder = builder.Columns(menuAuthRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*MenuAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultMenuAuthModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*MenuAuth, error) {

	builder = builder.Columns(menuAuthRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*MenuAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultMenuAuthModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultMenuAuthModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultMenuAuthModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMenuAuthIdPrefix, primary)
}

func (m *defaultMenuAuthModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", menuAuthRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMenuAuthModel) tableName() string {
	return m.table
}
