// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	menuFieldNames          = builder.RawFieldNames(&Menu{})
	menuRows                = strings.Join(menuFieldNames, ",")
	menuRowsExpectAutoSet   = strings.Join(stringx.Remove(menuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	menuRowsWithPlaceHolder = strings.Join(stringx.Remove(menuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMenuIdPrefix = "cache:menu:id:"
)

type (
	menuModel interface {
		Insert(ctx context.Context, data *Menu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Menu, error)
		Update(ctx context.Context, data *Menu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMenuModel struct {
		sqlc.CachedConn
		table string
	}

	Menu struct {
		Id                int64          `db:"id"`
		MenuId            int64          `db:"menu_id"`              // 菜单ID
		ParentMenuId      int64          `db:"parent_menu_id"`       // 父菜单ID
		Path              string         `db:"path"`                 // 路由路径
		Name              string         `db:"name"`                 // 组件名
		Component         sql.NullString `db:"component"`            // 组件路径
		Title             string         `db:"title"`                // 菜单名称
		Icon              sql.NullString `db:"icon"`                 // 菜单图标
		ShowBadge         int64          `db:"show_badge"`           // 是否显示徽标
		ShowTextBadge     sql.NullString `db:"show_text_badge"`      // 文本徽标内容
		IsHide            int64          `db:"is_hide"`              // 是否在菜单中隐藏
		IsHideTab         int64          `db:"is_hide_tab"`          // 是否在标签页中隐藏
		Link              sql.NullString `db:"link"`                 // 外部链接
		IsIframe          int64          `db:"is_iframe"`            // 是否为iframe
		KeepAlive         int64          `db:"keep_alive"`           // 是否缓存
		IsInMainContainer int64          `db:"is_in_main_container"` // 是否在主容器中
		CreateTime        time.Time      `db:"create_time"`          // 创建时间
		UpdateTime        time.Time      `db:"update_time"`          // 更新时间
		DeleteTime        sql.NullTime   `db:"delete_time"`          // 删除时间
	}
)

func newMenuModel(conn sqlx.SqlConn, c cache.NodeConf, opts ...cache.Option) *defaultMenuModel {
	return &defaultMenuModel{
		CachedConn: sqlc.NewNodeConn(conn, c.NewRedis(), opts...),
		table:      "`menu`",
	}
}

func (m *defaultMenuModel) Delete(ctx context.Context, id int64) error {
	menuIdKey := fmt.Sprintf("%s%v", cacheMenuIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, menuIdKey)
	return err
}

func (m *defaultMenuModel) FindOne(ctx context.Context, id int64) (*Menu, error) {
	menuIdKey := fmt.Sprintf("%s%v", cacheMenuIdPrefix, id)
	var resp Menu
	err := m.QueryRowCtx(ctx, &resp, menuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", menuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMenuModel) Insert(ctx context.Context, data *Menu) (sql.Result, error) {
	menuIdKey := fmt.Sprintf("%s%v", cacheMenuIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, menuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MenuId, data.ParentMenuId, data.Path, data.Name, data.Component, data.Title, data.Icon, data.ShowBadge, data.ShowTextBadge, data.IsHide, data.IsHideTab, data.Link, data.IsIframe, data.KeepAlive, data.IsInMainContainer, data.DeleteTime)
	}, menuIdKey)
	return ret, err
}

func (m *defaultMenuModel) Update(ctx context.Context, data *Menu) error {
	menuIdKey := fmt.Sprintf("%s%v", cacheMenuIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, menuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.MenuId, data.ParentMenuId, data.Path, data.Name, data.Component, data.Title, data.Icon, data.ShowBadge, data.ShowTextBadge, data.IsHide, data.IsHideTab, data.Link, data.IsIframe, data.KeepAlive, data.IsInMainContainer, data.DeleteTime, data.Id)
	}, menuIdKey)
	return err
}

func (m *defaultMenuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMenuIdPrefix, primary)
}

func (m *defaultMenuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", menuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMenuModel) tableName() string {
	return m.table
}
