// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roleMenuFieldNames          = builder.RawFieldNames(&RoleMenu{})
	roleMenuRows                = strings.Join(roleMenuFieldNames, ",")
	roleMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(roleMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	roleMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(roleMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRoleMenuIdPrefix           = "cache:roleMenu:id:"
	cacheRoleMenuRoleIdMenuIdPrefix = "cache:roleMenu:roleId:menuId:"
)

type (
	roleMenuModel interface {
		Insert(ctx context.Context, data *RoleMenu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RoleMenu, error)
		FindOneByRoleIdMenuId(ctx context.Context, roleId int64, menuId int64) (*RoleMenu, error)
		Update(ctx context.Context, data *RoleMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRoleMenuModel struct {
		sqlc.CachedConn
		table string
	}

	RoleMenu struct {
		Id         int64        `db:"id"`
		RoleId     int64        `db:"role_id"`     // 角色ID
		MenuId     int64        `db:"menu_id"`     // 菜单ID
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 删除时间
	}
)

func newRoleMenuModel(conn sqlx.SqlConn, c cache.NodeConf, opts ...cache.Option) *defaultRoleMenuModel {
	return &defaultRoleMenuModel{
		CachedConn: sqlc.NewNodeConn(conn, c.NewRedis(), opts...),
		table:      "`role_menu`",
	}
}

func (m *defaultRoleMenuModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	roleMenuIdKey := fmt.Sprintf("%s%v", cacheRoleMenuIdPrefix, id)
	roleMenuRoleIdMenuIdKey := fmt.Sprintf("%s%v:%v", cacheRoleMenuRoleIdMenuIdPrefix, data.RoleId, data.MenuId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, roleMenuIdKey, roleMenuRoleIdMenuIdKey)
	return err
}

func (m *defaultRoleMenuModel) FindOne(ctx context.Context, id int64) (*RoleMenu, error) {
	roleMenuIdKey := fmt.Sprintf("%s%v", cacheRoleMenuIdPrefix, id)
	var resp RoleMenu
	err := m.QueryRowCtx(ctx, &resp, roleMenuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roleMenuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleMenuModel) FindOneByRoleIdMenuId(ctx context.Context, roleId int64, menuId int64) (*RoleMenu, error) {
	roleMenuRoleIdMenuIdKey := fmt.Sprintf("%s%v:%v", cacheRoleMenuRoleIdMenuIdPrefix, roleId, menuId)
	var resp RoleMenu
	err := m.QueryRowIndexCtx(ctx, &resp, roleMenuRoleIdMenuIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? and `menu_id` = ? limit 1", roleMenuRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roleId, menuId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleMenuModel) Insert(ctx context.Context, data *RoleMenu) (sql.Result, error) {
	roleMenuIdKey := fmt.Sprintf("%s%v", cacheRoleMenuIdPrefix, data.Id)
	roleMenuRoleIdMenuIdKey := fmt.Sprintf("%s%v:%v", cacheRoleMenuRoleIdMenuIdPrefix, data.RoleId, data.MenuId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, roleMenuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoleId, data.MenuId, data.DeleteTime)
	}, roleMenuIdKey, roleMenuRoleIdMenuIdKey)
	return ret, err
}

func (m *defaultRoleMenuModel) Update(ctx context.Context, newData *RoleMenu) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	roleMenuIdKey := fmt.Sprintf("%s%v", cacheRoleMenuIdPrefix, data.Id)
	roleMenuRoleIdMenuIdKey := fmt.Sprintf("%s%v:%v", cacheRoleMenuRoleIdMenuIdPrefix, data.RoleId, data.MenuId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roleMenuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RoleId, newData.MenuId, newData.DeleteTime, newData.Id)
	}, roleMenuIdKey, roleMenuRoleIdMenuIdKey)
	return err
}

func (m *defaultRoleMenuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRoleMenuIdPrefix, primary)
}

func (m *defaultRoleMenuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roleMenuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRoleMenuModel) tableName() string {
	return m.table
}
