// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"admin-server/api/internal/pkg/globalkey"
	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	entityFieldNames          = builder.RawFieldNames(&Entity{})
	entityRows                = strings.Join(entityFieldNames, ",")
	entityRowsExpectAutoSet   = strings.Join(stringx.Remove(entityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	entityRowsWithPlaceHolder = strings.Join(stringx.Remove(entityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEntityIdPrefix   = "cache:entity:id:"
	cacheEntityNamePrefix = "cache:entity:name:"
)

type (
	entityModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Entity) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Entity, error)
		FindOneByName(ctx context.Context, name string) (*Entity, error)
		Update(ctx context.Context, session sqlx.Session, data *Entity) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Entity) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Entity, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Entity, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Entity, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Entity, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Entity, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultEntityModel struct {
		sqlc.CachedConn
		table string
	}

	Entity struct {
		Id         int64          `db:"id"`          // 主键
		Name       string         `db:"name"`        // 实体名称
		Type       int64          `db:"type"`        // 实体类型（1=公司，2=个体户，3=工作室等，4=个人， 5=其他）
		Contact    sql.NullString `db:"contact"`     // 联系人
		Phone      sql.NullString `db:"phone"`       // 联系电话
		Address    sql.NullString `db:"address"`     // 地址
		OwnerId    int64          `db:"owner_id"`    // 拥有者用户ID
		Status     int64          `db:"status"`      // 状态（1=正常，0=禁用）
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime   `db:"delete_time"` // 删除时间
		DelState   int64          `db:"del_state"`   // 删除状态 0:未删除 1:已删除
	}
)

func newEntityModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultEntityModel {
	return &defaultEntityModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`entity`",
	}
}

func (m *defaultEntityModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	entityIdKey := fmt.Sprintf("%s%v", cacheEntityIdPrefix, id)
	entityNameKey := fmt.Sprintf("%s%v", cacheEntityNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, entityIdKey, entityNameKey)
	return err
}
func (m *defaultEntityModel) FindOne(ctx context.Context, id int64) (*Entity, error) {
	entityIdKey := fmt.Sprintf("%s%v", cacheEntityIdPrefix, id)
	var resp Entity
	err := m.QueryRowCtx(ctx, &resp, entityIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", entityRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEntityModel) FindOneByName(ctx context.Context, name string) (*Entity, error) {
	entityNameKey := fmt.Sprintf("%s%v", cacheEntityNamePrefix, name)
	var resp Entity
	err := m.QueryRowIndexCtx(ctx, &resp, entityNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? and del_state = ? limit 1", entityRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEntityModel) Insert(ctx context.Context, session sqlx.Session, data *Entity) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{}
	data.DelState = globalkey.DelStateNo
	entityIdKey := fmt.Sprintf("%s%v", cacheEntityIdPrefix, data.Id)
	entityNameKey := fmt.Sprintf("%s%v", cacheEntityNamePrefix, data.Name)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, entityRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Name, data.Type, data.Contact, data.Phone, data.Address, data.OwnerId, data.Status, data.DeleteTime, data.DelState)
		}
		return conn.ExecCtx(ctx, query, data.Name, data.Type, data.Contact, data.Phone, data.Address, data.OwnerId, data.Status, data.DeleteTime, data.DelState)
	}, entityIdKey, entityNameKey)
}

func (m *defaultEntityModel) Update(ctx context.Context, session sqlx.Session, newData *Entity) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	entityIdKey := fmt.Sprintf("%s%v", cacheEntityIdPrefix, data.Id)
	entityNameKey := fmt.Sprintf("%s%v", cacheEntityNamePrefix, data.Name)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, entityRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.Name, newData.Type, newData.Contact, newData.Phone, newData.Address, newData.OwnerId, newData.Status, newData.DeleteTime, newData.DelState, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Name, newData.Type, newData.Contact, newData.Phone, newData.Address, newData.OwnerId, newData.Status, newData.DeleteTime, newData.DelState, newData.Id)
	}, entityIdKey, entityNameKey)
}

func (m *defaultEntityModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Entity) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if _, err := m.Update(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "EntityModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultEntityModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultEntityModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultEntityModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Entity, error) {

	builder = builder.Columns(entityRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Entity
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Entity, error) {

	builder = builder.Columns(entityRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Entity
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Entity, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(entityRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Entity
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultEntityModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Entity, error) {

	builder = builder.Columns(entityRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Entity
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Entity, error) {

	builder = builder.Columns(entityRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Entity
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultEntityModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultEntityModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheEntityIdPrefix, primary)
}

func (m *defaultEntityModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", entityRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultEntityModel) tableName() string {
	return m.table
}
