// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"admin-server/api/internal/pkg/globalkey"
	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	entityUserFieldNames          = builder.RawFieldNames(&EntityUser{})
	entityUserRows                = strings.Join(entityUserFieldNames, ",")
	entityUserRowsExpectAutoSet   = strings.Join(stringx.Remove(entityUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	entityUserRowsWithPlaceHolder = strings.Join(stringx.Remove(entityUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEntityUserIdPrefix             = "cache:entityUser:id:"
	cacheEntityUserEntityIdUserIdPrefix = "cache:entityUser:entityId:userId:"
)

type (
	entityUserModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *EntityUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EntityUser, error)
		FindOneByEntityIdUserId(ctx context.Context, entityId int64, userId int64) (*EntityUser, error)
		Update(ctx context.Context, session sqlx.Session, data *EntityUser) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *EntityUser) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*EntityUser, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*EntityUser, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*EntityUser, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*EntityUser, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*EntityUser, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultEntityUserModel struct {
		sqlc.CachedConn
		table string
	}

	EntityUser struct {
		Id         int64        `db:"id"`          // 主键
		EntityId   int64        `db:"entity_id"`   // 实体ID
		UserId     int64        `db:"user_id"`     // 用户ID
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 删除时间
		DelState   int64        `db:"del_state"`   // 删除状态 0:未删除 1:已删除
	}
)

func newEntityUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultEntityUserModel {
	return &defaultEntityUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`entity_user`",
	}
}

func (m *defaultEntityUserModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	entityUserEntityIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheEntityUserEntityIdUserIdPrefix, data.EntityId, data.UserId)
	entityUserIdKey := fmt.Sprintf("%s%v", cacheEntityUserIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, entityUserEntityIdUserIdKey, entityUserIdKey)
	return err
}
func (m *defaultEntityUserModel) FindOne(ctx context.Context, id int64) (*EntityUser, error) {
	entityUserIdKey := fmt.Sprintf("%s%v", cacheEntityUserIdPrefix, id)
	var resp EntityUser
	err := m.QueryRowCtx(ctx, &resp, entityUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", entityUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEntityUserModel) FindOneByEntityIdUserId(ctx context.Context, entityId int64, userId int64) (*EntityUser, error) {
	entityUserEntityIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheEntityUserEntityIdUserIdPrefix, entityId, userId)
	var resp EntityUser
	err := m.QueryRowIndexCtx(ctx, &resp, entityUserEntityIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `entity_id` = ? and `user_id` = ? and del_state = ? limit 1", entityUserRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, entityId, userId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEntityUserModel) Insert(ctx context.Context, session sqlx.Session, data *EntityUser) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	data.DelState = globalkey.DelStateNo
	entityUserEntityIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheEntityUserEntityIdUserIdPrefix, data.EntityId, data.UserId)
	entityUserIdKey := fmt.Sprintf("%s%v", cacheEntityUserIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, entityUserRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.EntityId, data.UserId, data.DeleteTime, data.DelState)
		}
		return conn.ExecCtx(ctx, query, data.EntityId, data.UserId, data.DeleteTime, data.DelState)
	}, entityUserEntityIdUserIdKey, entityUserIdKey)
}

func (m *defaultEntityUserModel) Update(ctx context.Context, session sqlx.Session, newData *EntityUser) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	entityUserEntityIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheEntityUserEntityIdUserIdPrefix, data.EntityId, data.UserId)
	entityUserIdKey := fmt.Sprintf("%s%v", cacheEntityUserIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, entityUserRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.EntityId, newData.UserId, newData.DeleteTime, newData.DelState, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.EntityId, newData.UserId, newData.DeleteTime, newData.DelState, newData.Id)
	}, entityUserEntityIdUserIdKey, entityUserIdKey)
}

func (m *defaultEntityUserModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *EntityUser) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if _, err := m.Update(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "EntityUserModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultEntityUserModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultEntityUserModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultEntityUserModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*EntityUser, error) {

	builder = builder.Columns(entityUserRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*EntityUser
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityUserModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*EntityUser, error) {

	builder = builder.Columns(entityUserRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*EntityUser
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityUserModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*EntityUser, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(entityUserRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*EntityUser
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultEntityUserModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*EntityUser, error) {

	builder = builder.Columns(entityUserRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*EntityUser
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityUserModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*EntityUser, error) {

	builder = builder.Columns(entityUserRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*EntityUser
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultEntityUserModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultEntityUserModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultEntityUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheEntityUserIdPrefix, primary)
}

func (m *defaultEntityUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", entityUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultEntityUserModel) tableName() string {
	return m.table
}
